import { useTranslation } from 'react-i18next';
import SectionHeader from '@/components/section-header';
import {
  useIndicatorsGrid,
  useRecommendations,
  usePositionStatus,
  useMacroPanel,
  usePositioning,
  useFarmgatePrice,
} from '@/hooks/useDashboard';
import { parseConclusion } from '@/utils/recommendation-parser';
import StrataRail, {
  type RailPanel,
} from '@/components/market-analysis/strata-rail';
import TechnicalsGauges from '@/components/market-analysis/technicals-gauges';
import FxGauges from '@/components/market-analysis/fx-gauges';
import PositioningGauges from '@/components/market-analysis/positioning-gauges';
import ReferenceStrata from '@/components/market-analysis/reference-strata';
import { hasReferenceData } from '@/components/market-analysis/helpers';
import EditorialAnalysis from '@/components/market-analysis/editorial-analysis';
import { useEntitlements } from '@/contexts/EntitlementsContext';
import { ENT } from '@/entitlements';

interface MarketAnalysisProps {
  targetDate?: string;
  className?: string;
}

// Split analysis into 3 buckets — same distribution as before
function split3(arr: string[]): [string[], string[], string[]] {
  if (arr.length === 0) return [[], [], []];
  const per = Math.ceil(arr.length / 3);
  return [arr.slice(0, per), arr.slice(per, per * 2), arr.slice(per * 2)];
}

export default function MarketAnalysis({
  targetDate,
  className,
}: MarketAnalysisProps) {
  const { t } = useTranslation();
  const { has } = useEntitlements();
  // Section II is composed of independently-gated strata: the technical/FX
  // gauges + editorial belong to the market section; positioning, macro and the
  // farmgate reference are their own features. A tier that has only `farmgate`
  // (e.g. Coop Essentiel) sees Section II with just the guaranteed-price block.
  const showMarket = has(ENT.SECTION_MARKET);
  const showMacro = has(ENT.FEATURE_MACRO_PANEL);
  const showPositioning = has(ENT.FEATURE_POSITIONING);
  const showFarmgate = has(ENT.FEATURE_FARMGATE);
  const { data: gridData, isLoading: gridLoading } =
    useIndicatorsGrid(targetDate);
  const { data: recoData, isLoading: recoLoading } =
    useRecommendations(targetDate);
  const { data: posData } = usePositionStatus(targetDate);
  const { data: macro } = useMacroPanel(targetDate);
  const { data: positioning } = usePositioning(targetDate);
  const { data: farmgate } = useFarmgatePrice(targetDate);

  // Disclaimer when the day's decision is ensemble but the LLM narrative was
  // generated by the legacy daily-analysis job (which still writes conclusions).
  // Removed once Phase 8 ships ensemble-aligned narratives.
  const decisionAlgo = posData?.source_algorithm;
  const narrativeAlgo = recoData?.source_algorithm;
  const showNarrativeMismatch =
    decisionAlgo === 'ensemble_v1_softgate_wrapper' &&
    narrativeAlgo !== undefined &&
    narrativeAlgo !== null &&
    narrativeAlgo !== 'ensemble_v1_softgate_wrapper';

  const isLoading = gridLoading || recoLoading;
  const recommendations = recoData?.recommendations;
  const parsed = recommendations
    ? parseConclusion(recommendations)
    : { analysis: [], watchlist: [] };
  const [bucketReco, bucketSupply, bucketTechnical] = split3(parsed.analysis);

  // Ordered by data cadence, fastest → slowest: daily gauges (Technicals, FX)
  // → weekly (Positioning & Supply) → seasonal/monthly references. The rail
  // pages through them one at a time; a stratum with no data is dropped from
  // the folio rather than rendered empty.
  const panels: RailPanel[] = [];
  if (showMarket) {
    panels.push({
      id: 'technicals',
      name: t('market.grp_technicals'),
      cadence: t('market.cad_daily'),
      content: (
        <TechnicalsGauges
          indicators={gridData?.indicators}
          contractCode={gridData?.contract_code}
          sessionDate={gridData?.date}
        />
      ),
    });
  }
  if (showMacro) {
    panels.push({
      id: 'fx',
      name: t('market.grp_fx'),
      cadence: t('market.cad_daily'),
      content: <FxGauges macro={macro} />,
    });
  }
  if (showPositioning) {
    panels.push({
      id: 'positioning',
      name: t('market.grp_positioning'),
      cadence: t('market.cad_weekly'),
      content: <PositioningGauges positioning={positioning} />,
    });
  }

  // Reference stratum: farmgate (gated by feature:farmgate) + ENSO (macro).
  // Pass only the entitled data so an un-entitled part is never rendered.
  const fgGated = showFarmgate ? farmgate : undefined;
  const macroRefGated = showMacro ? macro : undefined;
  if (hasReferenceData(fgGated, macroRefGated)) {
    panels.push({
      id: 'reference',
      name: t('market.grp_reference'),
      cadence: t('market.cad_seasonal'),
      content: <ReferenceStrata farmgate={fgGated} macro={macroRefGated} />,
    });
  }

  return (
    <div className={className}>
      <section style={{ padding: '32px 0 24px' }}>
        <SectionHeader numeral="II" title="Market Analysis" />

        {panels.length > 0 && <StrataRail panels={panels} />}

        {showMarket && (
          <>
            <div
              aria-hidden
              style={{
                height: 1,
                borderTop: '1px dotted var(--rule)',
                margin: '28px 0',
              }}
            />

            <EditorialAnalysis
              isLoading={isLoading}
              showNarrativeMismatch={showNarrativeMismatch}
              bucketReco={bucketReco}
              bucketSupply={bucketSupply}
              bucketTechnical={bucketTechnical}
              watchlist={parsed.watchlist}
            />
          </>
        )}
      </section>

      <style>{`
        @media (max-width: 1023px) {
          .market-grid { grid-template-columns: 1fr !important; }
        }
        /* One gauge per row on phones. Paging is what pays for the extra
           height, and a full-width ruler (~350px vs ~160px in a 2-col grid)
           is the difference between reading the marker and guessing it. */
        @media (max-width: 767px) {
          .gauges-row { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  );
}
