import type { CSSProperties } from 'react';
import SectionHeader from '@/components/section-header';
import {
  useIndicatorsGrid,
  useRecommendations,
  usePositionStatus,
  useMacroPanel,
  usePositioning,
  useFarmgatePrice,
} from '@/hooks/useDashboard';
import { parseConclusion } from '@/utils/recommendation-parser';
import TechnicalsGauges from '@/components/market-analysis/technicals-gauges';
import FxGauges from '@/components/market-analysis/fx-gauges';
import PositioningGauges from '@/components/market-analysis/positioning-gauges';
import ReferenceStrata from '@/components/market-analysis/reference-strata';
import EditorialAnalysis from '@/components/market-analysis/editorial-analysis';

interface MarketAnalysisProps {
  targetDate?: string;
  className?: string;
}

// Split analysis into 3 buckets — same distribution as before
function split3(arr: string[]): [string[], string[], string[]] {
  if (arr.length === 0) return [[], [], []];
  const per = Math.ceil(arr.length / 3);
  return [arr.slice(0, per), arr.slice(per, per * 2), arr.slice(per * 2)];
}

// Dotted rule marking a cadence boundary between gauge strata.
const dividerStyle: CSSProperties = {
  height: 1,
  borderTop: '1px dotted var(--rule)',
  marginBottom: 28,
};

export default function MarketAnalysis({
  targetDate,
  className,
}: MarketAnalysisProps) {
  const { data: gridData, isLoading: gridLoading } =
    useIndicatorsGrid(targetDate);
  const { data: recoData, isLoading: recoLoading } =
    useRecommendations(targetDate);
  const { data: posData } = usePositionStatus(targetDate);
  const { data: macro } = useMacroPanel(targetDate);
  const { data: positioning } = usePositioning(targetDate);
  const { data: farmgate } = useFarmgatePrice(targetDate);

  // Disclaimer when the day's decision is ensemble but the LLM narrative was
  // generated by the legacy daily-analysis job (which still writes conclusions).
  // Removed once Phase 8 ships ensemble-aligned narratives.
  const decisionAlgo = posData?.source_algorithm;
  const narrativeAlgo = recoData?.source_algorithm;
  const showNarrativeMismatch =
    decisionAlgo === 'ensemble_v1_softgate_wrapper' &&
    narrativeAlgo !== undefined &&
    narrativeAlgo !== null &&
    narrativeAlgo !== 'ensemble_v1_softgate_wrapper';

  const isLoading = gridLoading || recoLoading;
  const recommendations = recoData?.recommendations;
  const parsed = recommendations
    ? parseConclusion(recommendations)
    : { analysis: [], watchlist: [] };
  const [bucketReco, bucketSupply, bucketTechnical] = split3(parsed.analysis);

  return (
    <div className={className}>
      <section style={{ padding: '32px 0 24px' }}>
        <SectionHeader numeral="II" title="Market Analysis" />

        {/* Section II is ordered by data cadence, fastest → slowest:
            daily gauges (Technicals, FX) → weekly (Positioning & Supply) →
            seasonal/monthly references (guaranteed price, ENSO). Dotted rules
            mark the cadence boundaries. All rows share the 5-column grid. */}
        <TechnicalsGauges indicators={gridData?.indicators} />
        <FxGauges macro={macro} />

        <div aria-hidden style={dividerStyle} />

        <PositioningGauges positioning={positioning} />

        <div aria-hidden style={dividerStyle} />

        <ReferenceStrata farmgate={farmgate} macro={macro} />

        <div aria-hidden style={dividerStyle} />

        <EditorialAnalysis
          isLoading={isLoading}
          showNarrativeMismatch={showNarrativeMismatch}
          bucketReco={bucketReco}
          bucketSupply={bucketSupply}
          bucketTechnical={bucketTechnical}
          watchlist={parsed.watchlist}
        />
      </section>

      <style>{`
        @media (max-width: 1023px) {
          .market-grid { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 767px) {
          .gauges-row { grid-template-columns: repeat(3, minmax(0, 1fr)) !important; }
          .macro-row { grid-template-columns: repeat(2, minmax(0, 1fr)) !important; }
          .positioning-row { grid-template-columns: 1fr !important; }
        }
        @media (max-width: 479px) {
          .gauges-row { grid-template-columns: repeat(2, minmax(0, 1fr)) !important; gap: 16px !important; }
        }
      `}</style>
    </div>
  );
}
