"""add_mvp_schema_v1

Revision ID: e36e360fb184
Revises: 6bb1fe6300fe
Create Date: 2026-03-13 10:38:08.621059

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e36e360fb184"
down_revision: Union[str, Sequence[str], None] = "6bb1fe6300fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aud_pipeline_run",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("status", sa.VARCHAR(length=50), nullable=False),
        sa.Column("error", sa.TEXT(), nullable=True),
        sa.Column("row_count", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pl_algorithm_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("version", sa.VARCHAR(length=50), nullable=False),
        sa.Column("horizon", sa.VARCHAR(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_algorithm_version"),
    )
    op.create_table(
        "pl_fundamental_article",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("category", sa.VARCHAR(length=50), nullable=False),
        sa.Column("source", sa.VARCHAR(length=200), nullable=True),
        sa.Column("title", sa.VARCHAR(length=500), nullable=True),
        sa.Column("summary", sa.TEXT(), nullable=True),
        sa.Column("keywords", sa.TEXT(), nullable=True),
        sa.Column("sentiment", sa.VARCHAR(length=50), nullable=True),
        sa.Column("impact_synthesis", sa.TEXT(), nullable=True),
        sa.Column("llm_provider", sa.VARCHAR(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pl_fundamental_article_date"),
        "pl_fundamental_article",
        ["date"],
        unique=False,
    )
    op.create_table(
        "pl_weather_observation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("region", sa.VARCHAR(length=100), nullable=True),
        sa.Column("observation", sa.TEXT(), nullable=True),
        sa.Column("summary", sa.TEXT(), nullable=True),
        sa.Column("keywords", sa.TEXT(), nullable=True),
        sa.Column("impact_assessment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pl_weather_observation_date"),
        "pl_weather_observation",
        ["date"],
        unique=False,
    )
    op.create_table(
        "ref_exchange",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=20), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("timezone", sa.VARCHAR(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "aud_data_quality_check",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=True),
        sa.Column("check_name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["aud_pipeline_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "aud_llm_call",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_run_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.VARCHAR(length=50), nullable=False),
        sa.Column("model", sa.VARCHAR(length=100), nullable=False),
        sa.Column("prompt", sa.TEXT(), nullable=True),
        sa.Column("response", sa.TEXT(), nullable=True),
        sa.Column("input_tokens", sa.INTEGER(), nullable=True),
        sa.Column("output_tokens", sa.INTEGER(), nullable=True),
        sa.Column("cost_usd", sa.DECIMAL(precision=10, scale=6), nullable=True),
        sa.Column("latency_ms", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["aud_pipeline_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pl_algorithm_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version_id", sa.Uuid(), nullable=False),
        sa.Column("parameter_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_version_id"],
            ["pl_algorithm_version.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "algorithm_version_id", "parameter_name", name="uq_algorithm_config_param"
        ),
    )
    op.create_table(
        "ref_commodity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=20), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("exchange_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["ref_exchange.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "ref_trading_calendar",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("exchange_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("is_trading_day", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["ref_exchange.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "exchange_id", "date", name="uq_trading_calendar_exchange_date"
        ),
    )
    op.create_index(
        "ix_trading_calendar_date", "ref_trading_calendar", ["date"], unique=False
    )
    op.create_table(
        "ref_contract",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commodity_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.VARCHAR(length=20), nullable=False),
        sa.Column("contract_month", sa.VARCHAR(length=10), nullable=False),
        sa.Column("expiry_date", sa.DATE(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["commodity_id"],
            ["ref_commodity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "pl_contract_data_daily",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("open", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("high", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("low", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("close", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("volume", sa.INTEGER(), nullable=True),
        sa.Column("oi", sa.INTEGER(), nullable=True),
        sa.Column(
            "implied_volatility", sa.DECIMAL(precision=15, scale=6), nullable=True
        ),
        sa.Column("stock_us", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("com_net_us", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["ref_contract.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "contract_id", name="uq_contract_data_daily"),
    )
    op.create_index(
        "ix_contract_data_daily_date", "pl_contract_data_daily", ["date"], unique=False
    )
    op.create_table(
        "pl_derived_indicators",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("r3", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("r2", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("r1", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("pivot", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("s1", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("s2", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("s3", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("ema12", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("ema26", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macd", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macd_signal", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("rsi_14d", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("stochastic_k_14", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("stochastic_d_14", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("atr", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("atr_14d", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("volatility", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("bollinger", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("bollinger_upper", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("bollinger_lower", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("bollinger_width", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column(
            "close_pivot_ratio", sa.DECIMAL(precision=15, scale=6), nullable=True
        ),
        sa.Column("volume_oi_ratio", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("gain_14d", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("loss_14d", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("rs", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("daily_return", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["ref_contract.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "contract_id", name="uq_derived_indicators"),
    )
    op.create_index(
        "ix_derived_indicators_date", "pl_derived_indicators", ["date"], unique=False
    )
    op.create_table(
        "pl_indicator_daily",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version_id", sa.Uuid(), nullable=False),
        sa.Column("rsi_score", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macd_score", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("stochastic_score", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("atr_score", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("close_pivot", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("volume_oi", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("rsi_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macd_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("stoch_k_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("atr_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("close_pivot_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("vol_oi_norm", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("indicator_value", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("momentum", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macroeco_bonus", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("macroeco_score", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("final_indicator", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("decision", sa.VARCHAR(length=50), nullable=True),
        sa.Column("confidence", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("direction", sa.VARCHAR(length=50), nullable=True),
        sa.Column("eco", sa.TEXT(), nullable=True),
        sa.Column("composite_score", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_version_id"],
            ["pl_algorithm_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["ref_contract.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "date", "contract_id", "algorithm_version_id", name="uq_indicator_daily"
        ),
    )
    op.create_index(
        "ix_indicator_daily_date", "pl_indicator_daily", ["date"], unique=False
    )
    op.create_table(
        "pl_signal_component",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("contract_id", sa.Uuid(), nullable=False),
        sa.Column("indicator_name", sa.VARCHAR(length=50), nullable=False),
        sa.Column("raw_value", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column("normalized_value", sa.DECIMAL(precision=15, scale=6), nullable=True),
        sa.Column(
            "weighted_contribution", sa.DECIMAL(precision=15, scale=6), nullable=True
        ),
        sa.Column("algorithm_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["algorithm_version_id"],
            ["pl_algorithm_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["ref_contract.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_signal_component_date_contract",
        "pl_signal_component",
        ["date", "contract_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_signal_component_date_contract", table_name="pl_signal_component")
    op.drop_table("pl_signal_component")
    op.drop_index("ix_indicator_daily_date", table_name="pl_indicator_daily")
    op.drop_table("pl_indicator_daily")
    op.drop_index("ix_derived_indicators_date", table_name="pl_derived_indicators")
    op.drop_table("pl_derived_indicators")
    op.drop_index("ix_contract_data_daily_date", table_name="pl_contract_data_daily")
    op.drop_table("pl_contract_data_daily")
    op.drop_table("ref_contract")
    op.drop_index("ix_trading_calendar_date", table_name="ref_trading_calendar")
    op.drop_table("ref_trading_calendar")
    op.drop_table("ref_commodity")
    op.drop_table("pl_algorithm_config")
    op.drop_table("aud_llm_call")
    op.drop_table("aud_data_quality_check")
    op.drop_table("ref_exchange")
    op.drop_index(
        op.f("ix_pl_weather_observation_date"), table_name="pl_weather_observation"
    )
    op.drop_table("pl_weather_observation")
    op.drop_index(
        op.f("ix_pl_fundamental_article_date"), table_name="pl_fundamental_article"
    )
    op.drop_table("pl_fundamental_article")
    op.drop_table("pl_algorithm_version")
    op.drop_table("aud_pipeline_run")
    # ### end Alembic commands ###
